"""create scrape jobs

Revision ID: f9c4e31cd733
Revises: 001_initial
Create Date: 2026-07-23 20:56:54.594693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c4e31cd733'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scrape_job_status'), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_jobs_created', 'scrape_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_created_by_id'), 'scrape_jobs', ['created_by_id'], unique=False)
    op.create_index('ix_scrape_jobs_org_status', 'scrape_jobs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_organization_id'), 'scrape_jobs', ['organization_id'], unique=False)
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.drop_index(op.f('ix_scrape_jobs_organization_id'), table_name='scrape_jobs')
    op.drop_index('ix_scrape_jobs_org_status', table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_created_by_id'), table_name='scrape_jobs')
    op.drop_index('ix_scrape_jobs_created', table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
